name: Run test suites

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        erlang:
          - otp: "24"
            rebar3: "3.20"
          - otp: "25"
            rebar3: "3.22"
          - otp: "26"
            rebar3: "3.22"
          - otp: "27"
            rebar3: "3.24"

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlang.otp }}
          rebar3-version: ${{ matrix.erlang.rebar3 }}
      - name: setup redis cluster
        run: docker compose up -d --wait
      - name: eunit
        run: rebar3 eunit -v -c
      - name: cover report
        run: rebar3 cover -v
      - uses: actions/upload-artifact@v3
        with:
          name: cover
          path: _build/test/cover
      - name: teardown redis cluster
        if: always()
        run: docker compose down || true
