name: Run test suites

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        erlang:
          - otp: "27"
            rebar3: "3.24"

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlang.otp }}
          rebar3-version: ${{ matrix.erlang.rebar3 }}
      - name: pull redis image
        run: |
          source .env
          docker pull public.ecr.aws/docker/library/redis:${REDIS_TAG}
      - name: setup redis cluster
        run: docker compose up -d --wait
      - name: eunit
        run: rebar3 eunit -v -c
      - name: cover report
        run: rebar3 cover -v
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cover-rebar3_${{ matrix.erlang.rebar3 }}-otp_${{ matrix.erlang.otp }}
          path: _build/test/cover
      - name: teardown redis cluster
        if: always()
        run: docker compose down || true
